#!/bin/bash

# Compile Java files
javac -d bin -cp biuoop-1.4.jar:src $(find src -name "*.java")

# Check if compilation was successful
if [ $? -eq 0 ]; then
  # Run GeometryTester
  java -cp biuoop-1.4.jar:bin GeometryTester
else
  echo "Compilation failed. Exiting."
  exit 1
fi